- dplanner/android/app/google-services.json
- dplanner/lib/firebase_options.dart
- Firebase 연동 메일 변경
- jinoj0423@gmail.com 에서 dplanner2223@gmail.com 으로 메일 변경
> PR : Firebase 연동한 메일 변경 완료 (#27)

- dplanner/ios/Flutter/AppFrameworkInfo.plist
- dplanner/ios/Flutter/Debug.xcconfig
- dplanner/ios/Flutter/Release.xcconfig
- dplanner/ios/Podfile
- dplanner/ios/Podfile.lock
- dplanner/ios/Runner.xcodeproj/project.pbxproj
- dplanner/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- dplanner/ios/Runner.xcworkspace/contents.xcworkspacedata
- dplanner/ios/Runner/AppDelegate.swift
- dplanner/ios/Runner/Info.plist
> PR : iOS 로그인 - 네이버 (#38)

- dplanner/lib/pages/login_page.dart
> PR : 로그인 후 페이지 전환 (#44)

- dplanner/lib/controllers/member.dart
- dplanner/lib/models/club_member_model.dart
- dplanner/lib/pages/club_home_page.dart
- dplanner/lib/pages/club_join_next_page.dart
- dplanner/lib/pages/login_page.dart
- dplanner/lib/services/club_api_service.dart
- dplanner/lib/services/club_member_api_service.dart
- dplanner/lib/services/token_api_service.dart
- dplanner/lib/widgets/club_card.dart
- 로그인 하면서 최근 클럽 정보 및 클럽 멤버 정보 저장 및 홈화면 이동 설정
- club_member_api_service.dart 생성
- token으로 rename
> PR : 로그인 시 필요 데이터 저장 (#46)

- dplanner/.vscode/launch.json
- dplanner/ios/Podfile.lock
- dplanner/lib/models/post_comment_model.dart
- dplanner/lib/models/post_model.dart
- dplanner/lib/pages/club_home_page.dart
- dplanner/lib/pages/club_resource_list_page.dart
- dplanner/lib/pages/post_add_page.dart
- dplanner/lib/pages/post_page.dart
- dplanner/lib/routes.dart
- dplanner/lib/services/club_post_api_service.dart
- dplanner/lib/widgets/full_screen_image.dart
- dplanner/lib/widgets/mini_text_button.dart
- dplanner/lib/widgets/post_card.dart
- dplanner/lib/widgets/post_comment.dart
- dplanner/lib/widgets/post_content.dart
- dplanner/pubspec.yaml
- 클럽 게시글 리스트 불러오기
- 클럽 게시글 작성하기
- 클럽 게시글 이미지 자세히 보기
- 클럽 게시글 수정하기
- 클럽 게시글 삭제하기
- 클럽 게시글 좋아요 토글
- 클럽 게시글 댓글 불러오기
- 클럽 게시글 댓글쓰기
- 클럽 게시글 답댓글 토글
- 클럽 게시글 답댓글쓰기
- 클럽 댓글 삭제하기
post_comment_model.dart
post_model.dart
club_post_api_service.dart
full_screen_image.dart -> 추후 품목 반납시 이미지 자세히 보기에서도 사용할 수 있는 class
http_parser: ^4.0.2
flutter_image_compress: ^2.1.0
path_provider: ^2.1.2
> PR : 클럽 홈 게시글 api 연동 (#42)

- dplanner/android/app/build.gradle
- dplanner/lib/models/lock_model.dart
- dplanner/lib/pages/club_timetable_page.dart
- dplanner/lib/services/lock_api_service.dart
- dplanner/pubspec.yaml
- 락 목록 가져오기 api 연동
- 락 생성하기 api 연동
- 락 수정하기 api 연동
- 락 삭제하기 api 연동
- lock_model.dart 생성
- lock_api_service.dart 생성
> PR : 클럽 예약 락 api 연동 (#33)

- dplanner/lib/models/post_comment_model.dart
- dplanner/lib/models/post_model.dart
- dplanner/lib/pages/my_activity_check_page.dart
- dplanner/lib/pages/post_page.dart
- dplanner/lib/services/club_post_api_service.dart
- dplanner/lib/widgets/post_card.dart
- dplanner/lib/widgets/post_comment.dart
- dplanner/lib/widgets/post_content.dart
network image 로직 수정을 위해 우선 구현한 부분은 머지합니다
(게시글 리스트, 댓글, 댓글 리스트, 게시글에 프로필 로딩이 있음)
> Feat/65 게시판 수정사항 적용

- dplanner/ios/Podfile.lock
- dplanner/lib/models/post_comment_model.dart
- dplanner/lib/pages/club_home_page.dart
- dplanner/lib/pages/my_activity_check_page.dart
- dplanner/lib/pages/post_page.dart
- dplanner/lib/services/club_post_api_service.dart
- dplanner/lib/widgets/comment_mini_card.dart
- dplanner/lib/widgets/post_card.dart
- dplanner/lib/widgets/post_comment.dart
- dplanner/lib/widgets/post_content.dart
- 댓글 UI 들여쓰기 수정
- 댓글, 대댓글 UI 구조 수정
- 게시글 고정 기능 추가
- 내 댓글 보기 api 연동
> PR : 게시판 수정사항 적용 - 2 (#65)

- dplanner/lib/pages/login_page.dart
모바일 기종이 iOS 인 경우에만 apple login이 가능하도록 수정
> PR : 64 애플 로그인 구현 - 2(#64) 

- dplanner/lib/pages/post_page.dart
- dplanner/lib/widgets/post_card.dart
- dplanner/lib/widgets/post_content.dart
- 게시글 목록, 자세히보기 UI를 간단하게 수정했습니다
- 댓글달기에 들어가는 프로필 이미지 로직 통일했습니다
> PR : 게시판 수정사항 적용 - 3 (#65)

- dplanner/lib/pages/club_setting_page.dart
- dplanner/lib/pages/my_profile_modification_page.dart
> PR : 프로필 사진 변경 에러 해결 (#82)

- dplanner/lib/pages/club_my_page.dart
- dplanner/lib/pages/club_timetable_page.dart
- dplanner/lib/pages/my_reservation_tab1_page.dart
- dplanner/lib/pages/my_reservation_tab2_page.dart
- dplanner/lib/widgets/reservation_admin_card.dart
- dplanner/lib/widgets/reservation_big_card.dart
- dplanner/lib/widgets/reservation_mini_card.dart
- 내 예약 목록 상세 정보창 구현
- 거절된 예약 UI 변경
> PR : 예약 목록 눌렀을 때 예약 정보 보여주기 구현(#80)

- dplanner/lib/pages/club_management_page.dart
- dplanner/lib/pages/club_member_list_page.dart
- dplanner/lib/pages/club_my_page.dart
- dplanner/lib/pages/club_resource_list_page.dart
- dplanner/lib/pages/club_timetable_page.dart
- dplanner/lib/widgets/outline_textform.dart
- dplanner/lib/widgets/post_comment.dart
- dplanner/lib/widgets/post_content.dart
- dplanner/lib/widgets/snack_bar.dart
- 권한에 따른 기능 설정
- 매니저 권한
-마이페이지(tab3) 클럽 관리창 추가
- 게시글 관리 권한
-포스트(tab2) 권한 기능 설정
- 예약 관리 권한
-예약 시간표(tab1) 권한 기능 설정
-예약요청 페이지 진입 가능
- 멤버 관리 권한
-회원 목록(회원 승인/방출, 등급 조정) 권한 기능 설정 
- 공유 물품 관리 권한
-예약 시간표(tab1) 새 공유물품 추가 기능 설정
-공유 물품 목록(공유 물품 추가/수정/삭제) 권한 기능 설정
> PR : 관리자 및 매니저 권한에 따른 기능 분류 (#81)

- dplanner/lib/models/post_model.dart
- dplanner/lib/widgets/post_content.dart
- ClubMemberId 추가
- 포스트 모델에 ClubMemberId 추가
- 게시물 작성자와 앱 사용자 확인
> PR : post_model에 clubMemberId 추가 (#91)

- dplanner/lib/pages/club_management_page.dart
- dplanner/lib/pages/club_manager_list_page.dart
- dplanner/lib/pages/club_member_list_page.dart
- dplanner/lib/pages/club_resource_list_page.dart
- dplanner/lib/pages/club_timetable_page.dart
- dplanner/lib/style.dart
- dplanner/lib/widgets/post_comment.dart
- dplanner/lib/widgets/post_content.dart
- 일반 사용자/관리자에 따른 예약 색상 설정
- 노션에 기록
> PR : 예약락 색상 설정 (#93)

- dplanner/lib/models/resource_model.dart
- dplanner/lib/pages/club_resource_list_page.dart
- dplanner/lib/pages/club_timetable_page.dart
- dplanner/lib/services/resource_api_service.dart
- dplanner/lib/widgets/underline_textform.dart
- dplanner/pubspec.yaml
- 공유 자원에 유효기간 설정
- 각 공유 자원 유효기간에 따른 예약 화면 UI 변화 적용
- 공유 자원 추가 및 수정 시 유효기간 속성 추가
- 예약 화면에서 유효기간이외 범위는 락 색깔로 막아둠
- 예약 신청 화면의 날짜 선택 UI에서도 적용
> PR : 공유 자원 유효기간 속성 추가 (#88)

- dplanner/lib/pages/club_timetable_page.dart
- 예약 화면 및 날짜 선택 화면에서 에러 발생
- 예약 화면 조건문 잘못 정렬
- 날짜 선택 화면에서 관리자는 모든 날짜 선택 가능하게끔 설정
> PR : 예약 시간표 에러 수정 (#100)

- dplanner/lib/pages/club_timetable_page.dart
- 해당 달 락 목록 불러오기
- [yyyy년 MM월] 로 락 목록에서 해당 달 표현
> PR : 해당 달에 해당하는 락 목록 불러오기 (#104)

- dplanner/lib/pages/club_create_page.dart
- dplanner/lib/pages/club_create_success_next_page.dart
- dplanner/lib/pages/club_create_success_page.dart
- dplanner/lib/pages/club_info_page.dart
- dplanner/lib/pages/club_join_next_page.dart
- dplanner/lib/pages/club_join_page.dart
- 클럽 초대 코드 복사 기능 구현
- 클립 코드로 복사
- 페이지 정리
> PR : 클럽 초대 코드 복사 기능 구현 (#106)

- dplanner/lib/controllers/posts.dart
- dplanner/lib/main.dart
- dplanner/lib/models/post_model.dart
- dplanner/lib/pages/club_home_page.dart
- dplanner/lib/pages/my_activity_check_page.dart
- dplanner/lib/pages/post_add_page.dart
- dplanner/lib/pages/post_page.dart
- dplanner/lib/services/club_post_api_service.dart
- dplanner/lib/widgets/comment_block.dart
- dplanner/lib/widgets/my_activity_posts.dart
- dplanner/lib/widgets/outline_textform.dart
- dplanner/lib/widgets/post_card.dart
- dplanner/lib/widgets/post_comment.dart
- dplanner/lib/widgets/post_content.dart
- 검색창 삭제
- 댓글 수정 버튼 삭제
- 댓글 삭제시 답글이 남아있는 경우 별도 처리
- 게시글 변경 및 삭제가 즉시 반영되도록 변경
- 게시글및 댓글 아래로 스크롤시 부자연스럽게 잘리는 현상 해결
- 내 게시글 > 게시글 상세에서의 변경사항이 리스트에 바로 반영되도록 변경
- 답글 달기 선택시 입력창 문구 하이라이트
- 답글 삭제시 게시글에 즉시 반영
> Feat/108 게시판 개선

- dplanner/lib/pages/app_setting_page.dart
- dplanner/lib/pages/club_info_page.dart
- dplanner/lib/pages/club_list_page.dart
- dplanner/lib/pages/club_my_page.dart
- dplanner/lib/pages/setting_page.dart
- dplanner/lib/routes.dart
- dplanner/lib/services/club_api_service.dart
- 앱 설정, 로그아웃, 앱 탈퇴 버튼 이동
- 클럽 목록 옆 톱니바퀴 아이콘 생성 및 설정 페이지 생성
- settint_page.dart 생성
> PR : 앱 설정 앱 탈퇴 로그아웃 메뉴 이동 (#111)

- dplanner/lib/pages/club_info_page.dart
- dplanner/lib/pages/club_resource_list_page.dart
- dplanner/lib/pages/setting_page.dart
- dplanner/lib/services/member_service.dart
- 앱 탈퇴 api 연동
- member_service.dart 생성
> PR : 앱 탈퇴 api 연동 (#114)

- dplanner/lib/models/reservation_model.dart
- dplanner/lib/pages/club_reservation_list_tab2_page.dart
- dplanner/lib/pages/club_reservation_list_tab3_page.dart
- dplanner/lib/pages/club_timetable_page.dart
- dplanner/lib/pages/my_reservation_page.dart
- dplanner/lib/pages/my_reservation_tab1_page.dart
- dplanner/lib/pages/my_reservation_tab3_page.dart
- dplanner/lib/services/reservation_api_service.dart
- dplanner/lib/widgets/reservation_admin_card.dart
- dplanner/lib/widgets/reservation_big_card.dart
- dplanner/lib/widgets/reservation_return_card.dart
- 예약 거절 메시지 추가
- 관리자용 예약 목록에서 거절한 예약 거절 메시지 추가
- 내 예약 목록에 거절된 예약 탭 추가
- reservation model에 rejectMessage list 추가
- 예약 정보에 거절 사유 추가
> PR : 예약 거절 메시지 추가 (#116)

- dplanner/android/app/src/main/AndroidManifest.xml
- dplanner/ios/Runner/Info.plist
- dplanner/lib/const/report_message.dart
- dplanner/lib/pages/app_setting_page.dart
- dplanner/lib/pages/post_add_page.dart
- dplanner/pubspec.yaml
- 게시글 쓰는 곳 플레이스 홀더 문구 “부적절하거나 불쾌감을 줄 수 있는 컨텐츠를 게시할 경우 제재를 받습니다. 본인이 작성한 게시글이 타인에 의해 신고당할 경우 활동이 제한될 수 있습니다.” 로 수정
- 신고 항목 선택하는 경고창 아래에 “신고 내용은 24시간 이내에 조치됩니다” 라는 내용 추가
- 앱 설정 > 문의하기 누르면 dplanner2223@gmail.com으로 메일 보내는 화면  추가
> PR : 리젝 대응 게시글댓글 신고 보완 (#124)

- dplanner/lib/pages/app_setting_page.dart
> PR : 문의 내용에 로그인 정보 넣기 (#126)

- dplanner/lib/pages/post_page.dart
- dplanner/lib/widgets/post_card.dart
- dplanner/lib/widgets/post_content.dart
- 게시글 드래그 앤 복사 기능 추가
- 댓글 및 좋아요 버튼 터치 개선
- 댓글 버튼 터치 시 댓글 위치로 이동
- SelectableText 사용
> PR : 게시글 복사 기능 (#130)

- dplanner/lib/controllers/posts.dart
- dplanner/lib/services/club_post_api_service.dart
- dplanner/lib/widgets/post_content.dart
- 게시물 차단 기능 추가
- 게시물 차단 버튼 생성
- 게시물 차단 api 연동
> PR : 게시글과 회원 차단 및 필터링 (#129)

- dplanner/android/app/build.gradle
- dplanner/lib/services/club_member_api_service.dart
- dplanner/lib/widgets/comment_block.dart
- dplanner/lib/widgets/post_card.dart
- dplanner/lib/widgets/post_content.dart
- 회원 정보 조회 기능
- 타 회원 차단 기능
- postBlockClubMember api 연동
> PR : 회원 정보 조회 및 차단 기능 추가 (#134)

- dplanner/lib/widgets/comment_block.dart
- dplanner/lib/widgets/post_card.dart
> PR : 홈화면 및 댓글 창에서 회원 차단시 닫는 창 수정 (#136)

- dplanner/lib/controllers/posts.dart
- dplanner/lib/widgets/comment_block.dart
- dplanner/lib/widgets/post_card.dart
- dplanner/lib/widgets/post_content.dart
- 클럽 멤버 차단 후 화면 갱신
- 홈화면, 게시글, 댓글에서 모두 반영
> PR : 클럽 멤버 차단 후 화면 갱신 (#138)

- dplanner/android/app/build.gradle
> PR : 버전 코드 및 버전 이름 수정 (#140)

- dplanner/lib/widgets/comment_block.dart
- dplanner/lib/widgets/post_card.dart
- dplanner/lib/widgets/post_content.dart
- 사용자 본인 차단 안되게 수정
- 홈화면, 게시물, 답글에서 모두 반영
> PR : 본인 차단 안되게 수정 (#143)

- dplanner/lib/pages/club_timetable_page.dart
- 예약 화면에서 사용자 권한에 따른 예약 화면 개선
- 일반 사용자 입장에서는  공유물품 기한에 맞게 예약이 보이게 설정
- 관리자 입장에서는 공유물품 기한이 안 보이게 설정
> PR : 사용자 권한에 따른 공유물품 예약 가능 기간 표시 화면 개선 (#150)

- dplanner/lib/const/style.dart
- dplanner/lib/main.dart
- dplanner/lib/pages/club_manager_list_page.dart
- dplanner/lib/services/club_manager_api_service.dart
- dplanner/lib/widgets/comment_block.dart
- dplanner/lib/widgets/post_content.dart
- dplanner/pubspec.yaml
- 게시글, 댓글 Linkify
- ios status bar 노출
- 권한관리 버그 수정
> 게시물 하이퍼링크 추가 및 매니저 권한 변경 오류 수정

- dplanner/android/app/build.gradle
- dplanner/android/app/src/main/AndroidManifest.xml
- dplanner/lib/pages/club_timetable_page.dart
- 구글 플레이스토어 리젝 해결(권한 설정 수정)
- 예약 시 예약 가능 기간에 맞지 않게 예약 불가능한 부분 해결
- USE_FULL_SCREEN_INTENT, SCHEDULE_EXACT_ALARM, USE_EXACT_ALARM 권한 삭제
- 예약 가능 기간 변수 선언 부분 수정
> PR : 권한 설정 수정 및 예약 에러 해결 (#153)

- dplanner/lib/pages/club_timetable_page.dart
- dplanner/lib/services/reservation_api_service.dart
- 예약 주인 위임 기능 추가
- 예약 권한 보유자의 모든 사용자 예약 수정 가능 기능 추가
- 예약 이벤트 타일 단어 간 간격 조정
- 예약 신청 및 정보, 수정 화면에 예약자 필드 추가
- 예약자 수정 Api 연동
> PR : 예약 주인 위임 기능 추가 및 예약 시스템 정리(#155)

- dplanner/lib/widgets/post_card.dart
- dplanner/lib/widgets/post_content.dart
24시간제를 선택해서 12:55AM 등의 애매한 해석 해결
> PR : 게시물 시간 12시간제에서 24시간제로 변경 (#157)

- dplanner/lib/pages/club_management_page.dart
- dplanner/lib/pages/club_manager_list_page.dart
- dplanner/lib/pages/club_reservation_list_tab1_page.dart
- dplanner/lib/pages/club_reservation_list_tab2_page.dart
- dplanner/lib/pages/club_reservation_list_tab3_page.dart
- dplanner/lib/pages/club_timetable_page.dart
- dplanner/lib/services/reservation_api_service.dart
- dplanner/lib/widgets/notification_card.dart
- dplanner/lib/widgets/reservation_big_card.dart
- "반납 메시지 열람 권한"(RETURN_MSG_READ) 권한 추가
- SCHEDULE_ALL 권한은 더이상 반납 메시지 알림을 받지 않음
> feat: 반납 메시지 열람 권한 추가
